hw_1
M-Garkaviuk/django pull request #1
Opened 2023-10-09 14:03 UTC by M-Garkaviuk

hw_1

2023-10-10 14:45 UTC, PonomaryovVladyslav requested changes

2023-10-10 14:45 UTC, PonomaryovVladyslav commented on blog/urls.py
> +    path("", include("users.urls")),
Разбивать на 3 урла плохая идея, лучше сделать 3 приложения тогда уже

2023-10-10 14:45 UTC, PonomaryovVladyslav commented on users/urls.py
> +from users import views
Импортируй пожалуйста то что используешь, а то это ничем не отличается от import *

2023-10-11 10:37 UTC, PonomaryovVladyslav requested changes

2023-10-11 10:37 UTC, PonomaryovVladyslav commented on demo/views.py
> +def index(request):
Примеры из лекции тут что делают?))

2023-10-11 14:52 UTC, M-Garkaviuk commented on demo/views.py
> +def index(request):
Убрал. Случайно присели не на ту ветку )

2023-10-11 15:40 UTC, PonomaryovVladyslav approved these changes

2023-10-11 16:44 UTC, merged