Hw 3
M-Garkaviuk/django pull request #3
Opened 2023-10-13 20:06 UTC by M-Garkaviuk

HW_3

2023-10-14 02:26 UTC, PonomaryovVladyslav requested changes

2023-10-14 02:26 UTC, PonomaryovVladyslav commented on .idea/.gitignore
эта папка тут откуда?

2023-10-14 11:50 UTC, M-Garkaviuk commented on .idea/.gitignore
Неизвестно ) Вроде без звездочек добавлял - рука дрогнула. Удалил

2023-10-16 13:38 UTC, M-Garkaviuk commented on .idea/.gitignore
Не учел, что я ветку от непроверенной HW_2 создал для HW_3. Теперь удалил .idea/  в HW_3.

2023-10-16 13:54 UTC, PonomaryovVladyslav approved these changes

2023-10-16 13:57 UTC, merged